describe('Logoff', () => {
  it('passes', () => {
    cy.visit('/users/sign_in')
    cy.get('input[id="user_login"]')
      .type('root')
    cy.get('input[id="user_password"]')
      .type('emily123')
    cy.get('input[value="Sign in"]')
      .click()
    cy.get('H2[data-qa-selector="welcome_title_content"]')
      .contains('Welcome to GitLab')
    cy.get('a[class="header-user-dropdown-toggle"]').click()
    cy.get('a[data-qa-selector="sign_out_link"]').click()
    cy.get('h1[class="mb-3 font-weight-normal"]')
      .contains('GitLab Community Edition')
  })
})